site_name: Wiki Hadaria
site_description: Règlement officiel du serveur Hadaria
site_url: https://wiki.hadaria.fr/

theme:
  name: material
  custom_dir: overrides
  language: fr
  logo: https://www.hadaria.fr/_next/image?url=%2Flogo.webp&w=96&q=75
  favicon: https://www.hadaria.fr/_next/image?url=%2Flogo.webp&w=32&q=75
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair
  font:
    text: Geist
    code: Geist Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - toc.follow

extra_css:
  - stylesheets/extra.css

nav:
  - Accueil: index.md
  - Boutique: https://www.hadaria.fr/boutique
  - Voter: https://www.hadaria.fr/vote
  - Discord: https://discord.gg/hadaria
  - Règlements:
    - Règlement général: reglement-general.md
    - Règlement Évents PvP: reglement-events-pvp.md
    - Règlement Farm: reglement-farm.md
    - Règlement Pillage: reglement-pillage.md
  - 🎮 Jouer: https://www.hadaria.fr/#rejoindre

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables

plugins:
  - search:
      lang: fr
